[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
logfile_maxbytes=10MB
logfile_backups=3
loglevel=info
pidfile=/var/run/supervisord.pid

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx-stdout.log
stderr_logfile=/var/log/nginx-stderr.log
priority=10

[program:java]
command=java -jar /app/backend/app.jar
autostart=true
autorestart=true
stdout_logfile=/var/log/java-stdout.log
stderr_logfile=/var/log/java-stderr.log
environment=DATABASE_URL="%(ENV_DATABASE_URL)s",DB_USER="%(ENV_DB_USER)s",DB_PASS="%(ENV_DB_PASS)s",JWT_SECRET="%(ENV_JWT_SECRET)s"
priority=20
startsecs=10
startretries=5
